services:
  db:
    image: postgres:16
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  web:
    build: .
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_MASTER_KEY: ddfce4d1f12f66f9ce8c1499777e169b
      DATABASE_URL: postgres://postgres:password@db:5432/tiny_honey_production
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000/up" ]
      interval: 5s
      timeout: 5s
      retries: 5
